=== aaroncameron-wk/ArellePublic/arelle/doc/messagesCatalog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <element name="messages">
    <complexType>
      <sequence>
        <element maxOccurs="unbounded" ref="message"/>
      </sequence>
    </complexType>
  </element>
  <element name="message">
    <complexType>
        <complexContent>
          <restriction base="string">
              <attribute name="code" use="required" type="normalizedString"/>
              <attribute name="level" use="required" type="token"/>
              <attribute name="module" type="normalizedString"/>
              <attribute name="line" type="integer"/>
              <attribute name="args" type="NMTOKENS"/>
          </restriction>
        </complexContent>
    </complexType>
  </element>
</schema>

=== aaroncameron-wk/ArellePublic/arelle/doc/messagesCatalog.xml
<?xml version="1.0" encoding="utf-8"?>
<messages
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="messagesCatalog.xsd"
    variablePrefix="%("
    variableSuffix=")s"
    variablePrefixEscape="" >
<!-- 
This file contains Arelle messages text.   Each message has a code 
that corresponds to the message code in the log file, level (severity), 
args (available through log file), and message replacement text.

(Messages with dynamically composed error codes or text content 
(such as ValidateXbrlDTS.py line 158 or lxml parser messages) 
are reported as "(dynamic)".)

-->


<message code="EFM.6.12.06"
         level="warning"
         module="EdgarRenderer/Embedding.py" line="312"
         args="linkrole linkroleDefinition linkroleName numberRootConcepts">
[rq-1205-Multiple-Root-Nodes] Presentation relationship set role ''%(linkroleName)s'' has multiple (%(numberRootConcepts)s) root nodes. XBRL allows unordered root nodes, but rendering requires ordering.  They will instead be ordered by their labels.  To avoid undesirable ordering of axes and primary items across multiple root nodes, rearrange the presentation relationships to have only a single root node.”
</message>

<message code="EFM.6.12.07"
         level="warning"
         module="EdgarRenderer/Embedding.py" line="393"
         args="conceptTo conceptFrom linkrole linkroleDefinition linkroleName preferredLabel preferredLabelValue">
[rq-1207-Period-Type-Preferred-Label-Mismatch] In ''%(linkroleName)s'', element %(conceptTo)s has period type 'duration' but is given a preferred label %(preferredLabelValue)s when shown under parent %(parentQname)s.  The preferred label will be ignored.
</message>

<message code="EFM.6.12.08"
         level="warning"
         module="EdgarRenderer/PresentationGroup.py" line="271"
         args="axis linkrole linkroleDefinition linkroleName">
[rq-1208-Axis-Requires-Domain-Child] The presentation group ''%(linkroleName)s'' contains an axis %(axis)s with no domain element children, which effectively filters out every fact
</message>

<message code="EFM.6.12.09"
         level="warning"
         module="EdgarRenderer/Embedding.py" line="512"
         args="linkrole linkroleDefinition linkroleName foundMeasureSet missingMeasureSet">
[rq-1209-Presented-Units-Incomplete-Order] Units of measure %(foundMeasureSet)s were found in ''%(linkroleName)s'' but the facts presented use these additional units of measure: %(missingMeasureSet)s.  Add presentation relationships to provide a definite ordering of these additional units in the columns and rows of the output.
</message>

<message code="EFM.6.26.01"
         level="warning"
         module="EdgarRenderer/Cube.py" line="145"
         args="linkrole linkroleDefinition linkroleName axisSet">
[rq-2601-All-Facts-Filtered] The presentation group ''%(linkroleName)s'' contains %(axisSet)s, which either has (have) no default member in the presentation group. Since every fact is defaulted on this (these) axe(s), all facts have been filtered out.
</message>

<message code="EFM.6.26.02"
         level="warning"
         module="EdgarRenderer/Filing.py" line="949"
         args="fact value preferredLabel startOrEnd date linkrole linkroleDefinition linkroleName">
[rq-2602-Duration-Without-Matching-Instant] In ''%(linkroleName)s'', fact %(fact)s with value %(value)s and preferred label %(preferredLabel)s, was not shown because there are no facts in a duration %(startOrEnd)s at %(date)s. Change the preferred label role or add facts.
</message>

<message code="EFM.6.26.03"
         level="warning"
         module="EdgarRenderer/Cube.py" line="274"
         args="linkrole linkroleDefinition linkroleName">
The presentation base set ''%(linkroleName)s'' is a statement of changes in equity, but it has no duration-type facts matching the instant-type facts shown.  Add duration-type facts that represent the changes from instant to instant, or do not label the presentation base set a statement of changes.
</message>

<message code="EFM.6.26.04.embeddingCmdInvalidDomain"
         level="error"
         module="EdgarRenderer/Embedding.py" line="634"
         args="linkrole linkroleDefinition linkroleName fact contextID members axis">
[rq-2604-Embedding-Command-Invalid-Domain] In ''%(linkroleName)s'', the embedded report created by the embedding textBlock fact %(fact)s with the context %(contextID)s, the domain members %(members)s are not presentation descendants of %(axis)s.
</message>

<message code="EFM.6.26.04.embeddingCmdInvalidMemberOrMembers"
         level="error"
         module="EdgarRenderer/Filing.py" line="640"
         args="linkrole fact contextID linkroleDefinition linkroleName tokenlist">
[rq-2604-Embedding-Command-Invalid-Member-Or-Members] In ''%(linkrole)s'', the embedded report created by the embedding textBlock fact %(fact)s with the context %(contextID)s, the keywords %(tokenlist)s is not '*', a valid member qname or list of valid member qnames.
</message>

<message code="EFM.6.26.04.embeddingCmdMalformedAxis"
         level="error"
         module="EdgarRenderer/Filing.py" line="576"
         args="linkrole fact contextID linkroleDefinition linkroleName token position">
[rq-2604-Embedding-Command-Malformed-Axis] In ''%(linkrole)s'', the embedded report created by the embedding textBlock fact %(fact)s with the context %(contextID)s, the token %(token)s at position %(position)s in the list of tokens is malformed. This token can only be 'period', 'unit', 'primary' or identify an Axis by its namespace prefix, underscore, and element name.
</message>

<message code="EFM.6.26.04.embeddingCmdMalformedDirectionToken"
         level="error"
         module="EdgarRenderer/Filing.py" line="533"
         args="linkrole fact contextID linkroleDefinition linkroleName token position">
[rq-2604-Embedding-Command-Malformed-Direction-Token] In ''%(linkrole)s'', the embedded report created by the fact %(fact)s with the context %(contextID)s, the token %(token)s, at position %(position)s in the list of tokens, is malformed. Each iterator can only start with ‘row’ or ‘column’.
</message>

<message code="EFM.6.26.04.embeddingCmdMalformedStyleToken"
         level="error"
         module="EdgarRenderer/Filing.py" line="609"
         args="linkrole fact contextID linkroleDefinition linkroleName style">
[rq-2604-Embedding-Command-Malformed-Style-Token] In ''%(linkrole)s'', the embedded report created by the embedding textBlock fact %(fact)s with the context %(contextID)s, the style keyword %(style)s is not one of ‘compact’ or ‘nodisplay’.
</message>

<message code="EFM.6.26.05.embeddingCmdMissingIterator"
         level="error"
         module="EdgarRenderer/Embedding.py" line="241"
         args="linkrole linkroleDefinition linkroleName fact contextID iftransposed roworcol colorrow axes">
[rq-2605-Embedding-Command-Missing-Iterator] In ''%(linkroleName)s'', the embedded report created by the embedding textBlock fact %(fact)s with the context %(contextID)s, there are no valid %(roworcol)s commands%(iftransposed)s. Change one of the %(axes)s to a %(colorrow)s or add a %(roworcol)s command with an additional axis.
</message>

<message code="EFM.6.26.05.embeddingCmdMissingIteratorAfterTransposition"
         level="error"
         module="EdgarRenderer/Embedding.py" line="241"
         args="linkrole linkroleDefinition linkroleName fact contextID iftransposed roworcol colorrow axes">
[rq-2605-Embedding-Command-Missing-Iterator-After-Transposition] In ''%(linkroleName)s'', the embedded report created by the embedding textBlock fact %(fact)s with the context %(contextID)s, there are no valid %(roworcol)s commands%(iftransposed)s. Change one of the %(axes)s to a %(colorrow)s or add a %(roworcol)s command with an additional axis.
</message>

<message code="EFM.6.26.06"
         level="warning"
         module="EdgarRenderer/Embedding.py" line="147"
         args="linkrole linkroleDefinition linkroleName error axis embeddedCommand fact">
[rq-2606-Axis-Has-No-Order] In ''%(linkroleName)s'' the axis %(axis)s was not given an order in the presentation linkbase%(embeddedCommand)s. We arbitrarily chose an order by sorting on its label.
In ''%(linkroleName)s'', the embedded report created by the fact %(fact)s with context {context}, the axis %(axis)s was not given an order in the presentation base set {embeddedrole}. The axes are being sorted by their labels.
</message>

<message code="EFM.6.26.07"
         level="warning"
         module="EdgarRenderer/Report.py" line="1793"
         args="linkrole linkroleDefinition linkroleName fact contextID">
[rq-2607-Empty-Bar-Chart] In ''%(linkroleName)s'', the embedded report created by the embedding text block fact %(fact)s with context %(contextID)s, is a bar chart figure that has zero facts. If a bar chart figure is not wanted here, consider removing this particular text block fact, otherwise, determine why all its facts are being filtered out.
</message>

<message code="EFM.6.26.08"
         level="error"
         module="EdgarRenderer/Report.py" line="1194"
         args="linkrole linkroleDefinition linkroleName fact contextID numYears">
[rq-2608-Too-Many-Annual-Return-Facts] In ''%(linkroleName)s'', the embedded report created by the embedding textBlock fact %(fact)s with context %(contextID)s, there are %(numYears)s Annual Return Facts, but there must not be more than 20.
</message>

<message code="EFM.6.26.09"
         level="warning"
         module="EdgarRenderer/Embedding.py" line="589"
         args="linkrole linkroleDefinition linkroleName fact contextID">
[rq-2609-Primary-Axis-On-Rows] In ''{linkroleName}'' the embedded report created by the embedding text block fact {fact} with context {contextID} contains an iterator “column primary” even though the definition text of {linkroleDefinition} contains the “{Elements}” qualifier. The primary axis will remain on the rows.
</message>

<message code="er3:axisHasNoDefault"
